### ISSUE TITLE
Crash on App Launch

### ISSUE THREAD

**Issue by manasa246** [rahul-bangar/Transfinitte_App#1]
**Issue Summary:**
The app consistently crashes upon launch when running on Android 12 devices.

**Steps to Reproduce:**
1. Install the latest version of the app on an Android 12 device.
2. Launch the app.

**Expected Behavior:**
The app should launch successfully and display the main screen.

**Actual Behavior:**
The app crashes immediately before reaching the main screen. No error message is displayed to the user.

**Additional Information:**
- Android Device: Google Pixel 6 (Android 12)
- App Version: 2.0.1 (latest from Google Play)
- Reproducibility: The issue occurs consistently on Android 12 devices.
- Logs: Unfortunately, I could not find any error logs or crash reports on the device.

**Environment:**
- Android 12
- Google Pixel 6

**Note to Developers:**
Please investigate and resolve this issue, as Android 12 is an important platform for our app's user base.

Thank you for your attention to this matter.

**Comment by rahul-bangar** [comment]
**Issue Resolved**

**Resolution Details:**
Our development team diligently identified and remedied the root cause. The latest version, guarantees a stable and seamless experience on Android 12 devices.

**Action Required:**
Kindly update your app to the latest version via the Google Play Store.
